[package]
name = "pevm"
version = "0.1.0"
edition = "2021"

[dependencies]
# Put this behind a feature flag if there are use cases & users
# that need more security guarantees even for internally hashing
# EVM memory locations (we do not persist these hashes).
ahash = { version = "0.8.11", features = ["serde"] }
alloy-chains = "0.1.15"
alloy-primitives = { version = "0.7.2", features = ["asm-keccak"] }
alloy-rpc-types = "0.1"
bitvec = "1.0.1"
dashmap = "6.0.1"
defer-drop = "1.3.0"
serde = "1.0"

# Let's do our best to port needed REVM changes upstream
revm = { git = "https://github.com/risechain/revm", rev = "be291f3cede849c4a824f05c4ad6c014f8fb533a", features = [
    "serde",
] }

# RPC Storage dependencies
# TODO: Put these behind an RPC flag to not pollute the core
# library with RPC network & transport dependencies, etc.
alloy-provider = "0.1"
alloy-transport = "0.1"
alloy-transport-http = "0.1"
reqwest = "0.12.5"
tokio = { version = "1.38.0", features = ["rt-multi-thread"] }

[dev-dependencies]
alloy-consensus = "0.1"
alloy-rlp = "0.3.4"
alloy-trie = "0.4"
criterion = "0.5.1"
rand = "0.8.5"
rayon = "1.10.0"
revme = { git = "https://github.com/risechain/revm", rev = "be291f3cede849c4a824f05c4ad6c014f8fb533a" }
rpmalloc = { version = "0.2.2", features = ["thread_cache", "global_cache"] }
serde_json = "1.0.94"
walkdir = "2.5.0"

[lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.unreachable_pub = "warn"

[[bench]]
name = "mainnet"
harness = false

[[bench]]
name = "gigagas"
harness = false

[profile.release]
codegen-units = 1
panic = "abort"
lto = "fat"
